### PR TITLE
Rosbridge multiple rosapi fix and foxglove compatibility

### PR DESCRIPTION
**Pull request by mhl787156**
This PR provides a fix to the warnings which pop up for multiple rosapi nodes. The full issue has been raised here: https://github.com/RobotWebTools/rosbridge_suite/issues/704

This PR hopefully also addresses foxglove plotting and how why live plotting does not appear to work.

### CODE REVIEW

**Comment by mhl787156** [comment]
It now works! This is simulated trajectory. 

https://user-images.githubusercontent.com/10742598/150415059-6fd92c0d-56a6-48c4-837e-f4a1b28396ac.mp4

Note: that this whole stack needs quite a beefy computer otherwise lag factors in.

**Comment by mhl787156** [comment]
Created a temporary dockerfile at [mickeyli789/rosbridge-suite:v0.1.0](https://hub.docker.com/layers/188591048/mickeyli789/rosbridge-suite/v0.1.0/images/sha256-d9cea6008a715ec6af7e225209e4d3656d5962ba6a105e227d58faec8e0c1fc5?context=repo) which supports both runtime building of messages in env var `MSGS_WS` and plotting through foxglove. Currently used within mavros_controllers as plotting functionality and custom msgs needed asap.

**Comment by mhl787156** [comment]
Most recent version now has a working rosbirdge-suite build. 

Controllers in simulation must set the `use_sim_time` parameter for compatibility with foxglove. See https://github.com/foxglove/studio/issues/2697 for information. tl;dr foxglove uses whatever time is specified on the /clock topic. Also see here for how to set a node to use /clock as timesource: https://design.ros2.org/articles/clock_and_time.html

Proposal is base controller should have a `USE_SIMULATED_TIME` environment variable. Any controller launchfile should then have the following line:
```xml
<node pkg="mypkg" exec="controller ...>
    <param name="use_sim_time" value="$(env USE_SIMULATED_TIME false)"/>
   ...
</node>
```
- [ ] TODO: Document this point

**Review by rob-clarke — APPROVED** [review]
I'll add an issue to revert to the package binary once the patched version goes through sync.

**Pull request merged**
