### PR TITLE
Fenswood Tutorial Documentation

### PR DESCRIPTION
**Pull request by mhl787156**
This PR adds the tutorial documentation for the Fenswood Scenario for the Aerial MSc Tutorial session

### CODE REVIEW

**Review by rob-clarke — COMMENTED** [review]
My main comment would be, do we want this here or in Fenswood? Some of the content gets a bit too specific...

We can merge for now but we will need to look at making it less Fenswood/UoB in future

**Comment by rob-clarke** [comment]
Also, have we fixed the docs down bug when merging?

**Comment by mhl787156** [comment]
The Fenswood Scenario specific instructiosn have been moved over to the fenswood scenario repository. The version for this repo should be the generic example

**Comment by rob-clarke** [comment]
I've updated the docs with the fixes made the other day. I've kept it as Fenswood but just reworded some parts to make it more generic

**Review by rob-clarke — APPROVED** [review]

**Pull request merged**
