### PR TITLE
Add testing framework

### LINKED ISSUE #131: Document and Test Mavros
- [ ] Document
- [x] Create tests

Must test valid parsing of environment variables
(list env var combinations)

Must test integration with other systems

### LINKED ISSUE #132: Testing in Github ActionsGithub Actions Update
Incorporate bats (https://github.com/bats-core/bats-core) testing framework into github actions CI

### PR DESCRIPTION
**Pull request by rob-clarke**
Adds a testing framework to test images and integration

Example tests have been written for the `starling-mavros` image

### TODO
- [x] Add image tests to actions
- [x] Add integration test workflow

### CODE REVIEW

**Comment by rob-clarke** [comment]
I'd like to figure out the workflow properly before merging this. I think some sort of staging tag/area would be useful as we only want a fully consistent set of images to be pushed to the dev/latest/versioned tag. At the moment I think stage 1 images will be pushed without knowing if stage 2 / 3 images pass their tests successfully.

Potentially want to push all images to a staging area/tag then have a step similar to the current release step to actually add the final tags to the images / push them to docker hub.

**Comment by mhl787156** [comment]
I agree with you it does seem like a bad idea to push early ones without later ones being pushed. I will leave this in your capable hands! Shall we use github container registry? I assume that should be just as effective as Azure. Either that or you could create another organisation in docker for staging.

**Comment by rob-clarke** [comment]
Test infrastructure added and working.
Need to ensure that the correct images are being tested before merging

**Comment by rob-clarke** [comment]
The caching behaviour is a little unclear still, but on my machine the entire build is able to be skipped from cache on ghcr

Will need to watch that the "named" tags are updated correctly too when this makes it into dev/master

**Review by mhl787156 — DISMISSED** [review]
LGTM, only suggestion is to add in a Docs page about the approach? And also update the build docs.

**Review by mhl787156 — APPROVED** [review]

**Pull request merged**
